library(boot)
setwd("/home/thomas/Doutorado/PDSEproject/Project2/Program/AdvModel")
########################################################################
### Calculating R0
#####################################################################
##############################################################
dir = "FinalCode/May24/"
prob = 0.079
R0 = read.table(paste(dir,"result",prob,"Ef0.0PS0.0PV0.0_R0.dat",sep = ""),h = F)
mean(R0[,1])
points = boot(R0$V1,media,R = 300)
points$t
mean(points$t)

media<-function(x,idx){
  
  media1 = mean(x[idx])
  return(media1)
}


######################################################
### Calculating Proportion of infections generated by Symp/asymp for figure in suplemental material
####################################################################

prob = 0.079
PS = 0.4
step1 = 0.4
ef_values = seq(0.2,0.8,0.6)
prec_values = seq(step1,PS,step1)

ef_vector = c()
precV_vector = c()
proportionSymp = c()
proportionAsymp = c()


for(ef in ef_values){
  i = 1
  
  dados1 = read.table(paste(dir,"result",prob,"Ef",ef,"PS",PS,"PV0.0","_SympInf.dat",sep = ""),h = F)
  dados0 = read.table(paste(dir,"result",prob,"Ef",ef,"PS",PS,"PV0.0","_AsympInf.dat",sep = ""),h = F)
  proportionSymp[i] = mean(dados1$V1)/mean(dados1$V1+dados0$V1)
  proportionAsymp[i] = mean(dados0$V1)/mean(dados1$V1+dados0$V1)
  i = i+1
  for(pr in prec_values){
    
     dados1 = read.table(paste(dir,"result",prob,"Ef",ef,"PS",PS,"PV",pr,"_SympInf.dat",sep = ""),h = F)
     dados0 = read.table(paste(dir,"result",prob,"Ef",ef,"PS",PS,"PV",pr,"_AsympInf.dat",sep = ""),h = F)
     proportionSymp[i] = mean(dados1$V1)/mean(dados1$V1+dados0$V1)
     proportionAsymp[i] = mean(dados0$V1)/mean(dados1$V1+dados0$V1)
     i = i+1
  }
  prec_values2 = c(0.0,prec_values)
  dados = cbind(prec_values2,proportionSymp,proportionAsymp)
  
  write.table(dados,paste(dir,"Infections/result0",ef*10,".dat",sep = ""),row.names = F,col.names = F)
  
}

dados_baseline = read.table(paste(dir,"result",prob,"Ef0.0PS",PS,"PV0.0_SympInf.dat",sep = ""),h = F)
dados0_baseline = read.table(paste(dir,"result",prob,"Ef0.0PS",PS,"PV0.0_AsympInf.dat",sep = ""),h = F)
proportionSymp_baseline = mean(dados_baseline$V1)/mean(dados_baseline$V1+dados0_baseline$V1)
proportionAsymp_baseline = mean(dados0_baseline$V1)/mean(dados_baseline$V1+dados0_baseline$V1)
for(ef in ef_values){
  
  aux = read.table(paste(dir,"Infections/result0",ef*10,".dat",sep = ""),h = F)
  
  aux$V2 = -(aux$V2-proportionSymp_baseline)/proportionSymp_baseline
  aux$V3 = -(aux$V3-proportionAsymp_baseline)/proportionAsymp_baseline
  write.table(aux,paste(dir,"Infections/result0",ef*10,"relative.dat",sep = ""),row.names = F,col.names = F)
  
}

#####################################################################################
### Simple Incidence Plot
#####################################################################

dados1 = read.table(paste(dir,"result0.079Ef0.0PS0.4PV0.0_symp.dat",sep = ""),h = F)
a=seq(1,nrow(dados1),1)

limit=c(1,150)
xlimit = c(1,100)
plot(a,dados1[,1],type="l",col = "lightgrey",ylim = limit,xlab = "Time (weeks)",ylab = "Symptomatic infections incidence",xlim = xlimit)
for(i in 2:ncol(dados1)){
  
  lines(a,dados1[,i],col = "lightgrey")
  
}
lines(a,rowMeans(dados1),lwd=3,col = "black")

#############################################################################################
### Matrix of contact distribution
#############################################################3

dir = "FinalCode/May24/"
Ef = 0.0
PS = 0.4
PV = "0.0"
x = read.table(paste(dir,"result0.079Ef0.",Ef,"PS",PS,"PV",PV,"_ContactMatrixGeneral.dat",sep = ""), h=F)
y = read.table(paste(dir,"result0.079Ef0.",Ef,"PS",PS,"PV",PV,"_NumAgeGroup.dat",sep = ""), h=F)

aux = rep(0,15)


  for(i in 1:nrow(y)){
    for(j in 1:ncol(y)){
      aux[y[i,j]]=aux[y[i,j]]+1
    }
  }

aux = aux/ncol(y)


for(i in 1:15){
  
  x[,i] = x[,i]/aux[i]
  
}

write.table(x,paste(dir,"result0.079Ef0.",Ef,"PS",PS,"PV",PV,"_ContactPerInd.dat",sep = ""), row.names = F,col.names = F)


######################################################################
######### CALCULATING THE RISK ##################
##########################

EF = c(2,8)
ps = c(4,8)
PS = 4
for(PS in ps){
  ef = 0
  PV = 0

dataTouch <- read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_FailVector.dat",sep = ""),h = F)
dataInf <- read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_InfOrNot.dat",sep = ""),h = F)
dataTouch = dataTouch+dataInf
dataAge = read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_NumAgeGroup.dat",sep = ""),h = F)
dataVac = read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_VacStatus.dat",sep = ""),h = F)

aux1 = colSums(dataInf)

dataTouch = dataTouch[,aux1 > 0]
dataInf = dataInf[,aux1 > 0]
dataAge = dataAge[,aux1 > 0]
dataVac = dataVac[,aux1 > 0]


ResultVac = matrix(NA,nrow = ncol(dataTouch),ncol = 15)
ResultNVac = matrix(NA,nrow = ncol(dataTouch),ncol = 15)

Teste = CalcResult2(dataTouch,dataInf,dataAge,dataVac,ResultNVac,ResultVac)

write.table(Teste$NVac,paste(dir,forprint,"ResultsRisk/SuscEf0",ef,"PS0",PS,"PV0",PV,".dat",sep = ""),row.names = F,col.names = F)
write.table(Teste$Vac,paste(dir,forprint,"ResultsRisk/VacEf0",ef,"PS0",PS,"PV0",PV,".dat",sep = ""),row.names = F,col.names = F)



PV1 = c(0,PS)
  for(ef in EF){
    for(PV in PV1){
      print(c(ef,PV))
    dataTouch <- read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_FailVector.dat",sep = ""),h = F)
    dataInf <- read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_InfOrNot.dat",sep = ""),h = F)
    dataTouch = dataTouch+dataInf
    dataAge = read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_NumAgeGroup.dat",sep = ""),h = F)
    dataVac = read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_VacStatus.dat",sep = ""),h = F)
    
    aux1 = colSums(dataInf)
    
    dataTouch = dataTouch[,aux1 > 0]
    dataInf = dataInf[,aux1 > 0]
    dataAge = dataAge[,aux1 > 0]
    dataVac = dataVac[,aux1 > 0]
    
    
    ResultVac = matrix(NA,nrow = ncol(dataTouch),ncol = 15)
    ResultNVac = matrix(NA,nrow = ncol(dataTouch),ncol = 15)
    
    Teste = CalcResult2(dataTouch,dataInf,dataAge,dataVac,ResultNVac,ResultVac)
    
    write.table(Teste$NVac,paste(dir,forprint,"ResultsRisk/SuscEf0",ef,"PS0",PS,"PV0",PV,".dat",sep = ""),row.names = F,col.names = F)
    write.table(Teste$Vac,paste(dir,forprint,"ResultsRisk/VacEf0",ef,"PS0",PS,"PV0",PV,".dat",sep = ""),row.names = F,col.names = F)
    }
    
  }

}


CalcResult2 = function(dataTouch,dataInf,dataAge,dataVac,ResultNVac,ResultVac){
  for(agegroup in 1:15){
    
    m = 1
    k = 1
    MeanTouchVac = c()
    MeanTouchNonVac = c()
    for(i in 1:ncol(dataTouch)){
      
      
      ##############################################################
      
      ###FOR Non-VACCINATED
      aux1 = dataTouch[dataVac[,i] == 0,i]#Taking the non-vaccinated ones
      aux2 = dataInf[dataVac[,i] == 0,i]
      aux3 = dataAge[dataVac[,i] == 0,i]
      
      aux1 = aux1[aux3 == agegroup]##the age group
      aux2 = aux2[aux3 == agegroup]
      
      
      
      
      MeanTouchNonVac[k] = sum(aux2)/sum(aux1)
      k = k+1
      
      ##############################################################
      ###FOR VACCINATED
      aux1 = dataTouch[dataVac[,i] == 1,i]#Taking the vaccinated ones
      aux2 = dataInf[dataVac[,i] == 1,i]
      aux3 = dataAge[dataVac[,i] == 1,i]
    
      aux1 = aux1[aux3 == agegroup] ##the age group
      aux2 = aux2[aux3 == agegroup]
      
     
      MeanTouchVac[m] = (sum(aux2)/sum(aux1))
      m = m+1
      
      
     
    }
    if(length(MeanTouchNonVac)>0){
      ResultNVac[1:length(MeanTouchNonVac),agegroup] = MeanTouchNonVac
    }
    if(length(MeanTouchVac)>0){
      ResultVac[1:length(MeanTouchVac),agegroup] = MeanTouchVac
    }
  }
  lista = list("NVac" = ResultNVac,"Vac" = ResultVac)
  return(lista)
}


###########################################################################################
###Relative Proportion of infections

library("ggplot2")


ef = 0
PV = 0
PS = 4
NonVaccineInf = read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_InfOrNot.dat",sep = ""),h = F)
NonVaccineAge = read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_NumAgeGroup.dat",sep = ""),h = F)

data = NonVaccineAge[NonVaccineInf == 1]

data2 = NonVaccineAge[NonVaccineInf == 0]

NonVaccineInfected = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
NonVaccineNonInfected = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)

for(i in 1:length(data)){
  NonVaccineInfected[data[i]] = NonVaccineInfected[data[i]] + 1
}
  
for(i in 1:length(data2)){
  NonVaccineNonInfected[data2[i]] = NonVaccineNonInfected[data2[i]] + 1
}
ProportionNonVaccine = NonVaccineInfected/(NonVaccineInfected+NonVaccineNonInfected)


EF = c(2,8)
pv = c(0,PS)

count = 1
MatrixResult = matrix(0,nrow = 15,ncol = 4)
for(ef in EF){
  for(PV in pv){
    print(c(PV,ef))
VaccineInf = read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_InfOrNot.dat",sep = ""),h = F)
VaccineAge = read.table(paste(dir,"result0.079Ef0.",ef,"PS0.",PS,"PV0.",PV,"_NumAgeGroup.dat",sep = ""),h = F)

data = VaccineAge[VaccineInf == 1]

data2 = VaccineAge[VaccineInf == 0]

VaccineInfected = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
VaccineNonInfected = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)

for(i in 1:length(data)){
  VaccineInfected[data[i]] = VaccineInfected[data[i]] + 1
}

for(i in 1:length(data2)){
  VaccineNonInfected[data2[i]] = VaccineNonInfected[data2[i]] + 1
}

ProportionVaccine = VaccineInfected/(VaccineInfected+VaccineNonInfected)
MatrixResult[,count] = ProportionVaccine/ProportionNonVaccine
count = count + 1
}
}

disp = seq(1,15)
MatrixResult = data.frame(MatrixResult)
colnames(MatrixResult) = c("Ef02PV0",paste("Ef02PV0",PS,sep = ""),"Ef08PV0",paste("Ef08PV0",PS,sep = ""))
write.table(MatrixResult,paste(dir,"RelInfPS0",PS,".dat",sep = ""),row.names = F)

gg = ggplot(data = MatrixResult)

#gg = gg+ geom_map(map_id = "1.1",map = positions,fill = "lightgrey")
gg = gg+geom_line(mapping = aes(x = disp,y = MatrixResult[,1]),colour = "red",size = 1.2)
gg = gg+geom_line(mapping = aes(x = disp,y = MatrixResult[,2]),colour = "blue",size = 1.2)
gg = gg+geom_line(mapping = aes(x = disp,y = MatrixResult[,3]),colour = "green",size = 1.2)
gg = gg+geom_line(mapping = aes(x = disp,y = MatrixResult[,4]),colour = "black",size = 1.2)
gg = gg+geom_point(mapping = aes(x = disp,y = MatrixResult[,1]),colour = "red",size = 1.8)
gg = gg+geom_point(mapping = aes(x = disp,y = MatrixResult[,2]),colour = "blue",size = 1.8)
gg = gg+geom_point(mapping = aes(x = disp,y = MatrixResult[,3]),colour = "green",size = 1.8)
gg = gg+geom_point(mapping = aes(x = disp,y = MatrixResult[,4]),colour = "black",size = 1.8)

gg = gg+theme_bw()+labs(x = "Age Group",y = "Relative Risk")
gg


############################################################
############# Simple plot for median (IT IS NECESSARY THAT ONE HAS RUN THE "CALCULATING RISK" ABOVE)
#################################################################

EF = c(2,8)
ps = c(4,8)
par(mfrow = c(2,2))

for(ef in EF){
  for(PS in ps){
    PV = 0
    IndType = "Susc"
    Mediana = CalcMedian(PS,PV,ef,dir,IndType)
    plot(Mediana,col = "black",ylim = c(0,0.06),type = "l",main = paste("ef",ef,"PS",PS))
    
    IndType = "Vac"
    Mediana = CalcMedian(PS,PV,ef,dir,IndType)
    lines(Mediana,col = "red")
    
    PV = PS
    IndType = "Susc"
    Mediana = CalcMedian(PS,PV,ef,dir,IndType)
    lines(Mediana,col = "blue")
    
    IndType = "Vac"
    Mediana = CalcMedian(PS,PV,ef,dir,IndType)
    lines(Mediana,col = "green")
    
   }
}


CalcMedian <- function(PS,PV,ef,dir,IndType){
  
  x = read.table(paste(dir,"ResultsRisk/",IndType,"Ef0",ef,"PS0",PS,"PV0",PV,".dat",sep = ""), h = F)
  
  mediana = c()
  
  for(i in 1:15){
    aux = c()
    count = 1
    for(j in 1:nrow(x)){
      
      if(!is.na(x[j,i])){
        aux[count] = x[j,i]
        count = count+1
      }
      
    }
    mediana[i] = median(aux)
    
  }
  return(mediana)
  
}


###################################################33
################Heatmap
#############################################################


prob = 0.079
PS = 0.8
step1 = 0.02

dados0 = read.table(paste("result",prob,"Ef0.0PS",PS,"PV0.0_symp.dat",sep = ""), h = F)
dados02 = read.table(paste("result",prob,"Ef0.0PS",PS,"PV0.0_asymp.dat",sep = ""), h = F)
s0 = sum(dados0)
s02 = sum(dados0+dados02)
ef_values = seq(0.2,0.8,step1)
prec_values = seq(step1,0.8,step1)
ef_vector = c()
precV_vector = c()
proportion = c()
proportion2 = c()
i = 1
#setwd("/home/thomas/Doutorado/PDSEproject/Project2/Program/AdvModel/PrecautionS04/")
for(ef in ef_values){
  ef_vector[i] = ef
  precV_vector[i] = 0.0
  dados1 = read.table(paste("result",prob,"Ef",ef,"PS",PS,"PV0.0_symp.dat",sep = ""),h = F)
  dados2 = read.table(paste("result",prob,"Ef",ef,"PS",PS,"PV0.0_asymp.dat",sep = ""),h = F)
  proportion[i] = sum(dados1)/s0
  proportion2[i] = sum(dados1+dados2)/s02
  i = i+1
  for(precV in prec_values){
    ef_vector[i] = ef
    precV_vector[i] = precV
    dados1 = read.table(paste("result",prob,"Ef",ef,"PS",PS,"PV",precV,"_symp.dat",sep = ""),h = F)
    dados2 = read.table(paste("result",prob,"Ef",ef,"PS",PS,"PV",precV,"_asymp.dat",sep = ""),h = F)
    proportion[i] = sum(dados1)/s0
    proportion2[i] = sum(dados1+dados2)/s02
    i = i+1
  }
}

results = cbind(ef_vector,precV_vector,proportion)
write.table(results,"HeatmapResult_symp.dat", row.names = F,col.names = F)
results2 = cbind(ef_vector,precV_vector,proportion2)
write.table(results2,"HeatmapResult_Total.dat", row.names = F,col.names = F)


M1 = matrix(proportion,nrow = 41,ncol = 31)
write.table(M1,"HeatmapMatrixPS08_symp.dat", row.names = F,col.names = F)
M2 = matrix(proportion2,nrow = 41,ncol = 31)
write.table(M2,"HeatmapMatrixPS08_Total.dat", row.names = F,col.names = F)
#############################################################
##########################################################

